
import { 
    LayoutDashboard, 
    Building2, 
    ClipboardList, 
    Truck, 
    Users, 
    FileText, 
    Settings, 
    LogOut, 
    ChevronDown, 
    PlusCircle,
    BarChart3,
    AlertTriangle,
    CheckCircle2,
    XCircle,
    Clock,
    DollarSign,
    Sparkles,
    Send,
    Loader2,
    Copy,
    Bell,
    GanttChartSquare,
    Calculator,
    Fuel,
    UserCheck,
    Menu,
    Plus,
    ListOrdered,
    ClipboardPlus,
    History,
    CheckSquare,
    FileCheck,
    Upload,
    Receipt,
    FileDigit,
    HandCoins,
    Printer,
    FileImage,
    Award,
    Ruler,
    Trash2,
    Download
} from 'lucide-react';

export const Icons = {
    Dashboard: LayoutDashboard,
    Project: Building2,
    Tasks: ClipboardList,
    Inventory: Truck,
    Team: Users,
    Reports: BarChart3,
    Settings: Settings,
    Logout: LogOut,
    ChevronDown: ChevronDown,
    Add: Plus,
    Alert: AlertTriangle,
    Success: CheckCircle2,
    Error: XCircle,
    Pending: Clock,
    Budget: DollarSign,
    AI: Sparkles,
    Send: Send,
    Spinner: Loader2,
    Documents: FileText,
    Copy: Copy,
    Notifications: Bell,
    Gantt: GanttChartSquare,
    Financials: Calculator,
    Fuel: Fuel,
    Attendance: UserCheck,
    Menu: Menu,
    Orders: ListOrdered,
    LogUsage: ClipboardPlus,
    ConsumptionHistory: History,
    Approve: CheckSquare,
    Invoice: FileCheck,
    Upload: Upload,
    Receipt: Receipt,
    ClientInvoice: FileDigit,
    Revenue: HandCoins,
    Printer: Printer,
    FileImage: FileImage,
    Award: Award,
    Ruler: Ruler,
    Trash: Trash2,
    Download: Download,
};